### PR TITLE
Config profiles in sendto, customise environment and severities

### PR DESCRIPTION
**Pull request by satterly**
Allow users to customise the Zabbix-Alerta integration by:

* defining config profiles
* using zabbix severity levels and colours
* supporting `${ENVIRONMENT}` user macro
* providing deep links from Alerta to Zabbix
* mapping more zabbix attribute values

### CODE REVIEW

**Comment by satterly** [comment]
Will fix README formatting in a subsequent PR.

**Comment by satterly** [comment]
@been2io Would you be interested in testing this new version of the Zabbix->Alerta integration? It has some new features that may be useful to you and I'd appreciate some feedback. Thanks, Nick.

**Comment by paskal** [comment]
@satterly, I'll test it with Zabbix 3.0 and will report if there are any issues with the doc\script. Thanks for all the work!

**Comment by satterly** [comment]
@paskal That would be great. Cheers.

**Pull request merged**
